### ISSUE TITLE
Handling disconnected graphs

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#12]
When a graph is disconnected and packing of components is enabled **and** a cluster spans multiple components, we should merge the multiple components spanning the same cluster and process accordingly. In other words, the fact that two nodes are in the same cluster should force the components that these nodes are in to be *combined*.

**Comment by ugurdogrusoz** [comment]
This does not work. Load sample and group highlighted nodes together showing groups as circles and you get:
![visuall (2)](https://user-images.githubusercontent.com/3874988/101343077-81dd2080-3894-11eb-8044-da3a41fb75f6.png)

**Comment by ugurdogrusoz** [comment]
After having struggled selecting the two nodes, I finally produced this problem:
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/3874988/101356682-7c3e0580-38a9-11eb-8bef-2978768752a4.gif)

**Comment by canbax** [comment]
below gif is how I reproduce this bug. Also, I noticed sometimes Shift + Drag zooms in but I don't know how it happens. This should be related to the view-utilities extension because Visuall uses it for marquee zooming. (Visuall only changes the cursor on ctrl+shift pressed together)

![RMWVpwLqna](https://user-images.githubusercontent.com/8426741/101454639-5add2800-3942-11eb-9578-c18079a790a9.gif)
