### ISSUE TITLE
In circle nodes overlapping

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#21]
- Load the following graph
- Run layout with "Max Ratio Of Nodes Inside Circle" equal to 0.9
- We get in circle nodes overlapping. Shouldn't repulsion among these nodes repel them away, resulting in the circle expanding?
<img width="1112" alt="Screen Shot 2021-03-23 at 08 49 03" src="https://user-images.githubusercontent.com/3874988/112099481-a4c9e100-8bb4-11eb-9554-c444fcbafcc0.png">

[random_mesh(26).graphml.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-cise/files/6187167/random_mesh.26.graphml.txt)

**Comment by herencalik** [comment]
When several inner nodes put on to the center of the circle and the radius of the circle does not let any movement inside, the displacement of the overlapping nodes is extremely small. Even though the displacements are small, they make the circle expand, however, after many iterations. Before some number of expansions inner nodes cannot move inside the inner boundaries so this improper equilibrium continues. Therefore, instead of moving inner nodes to random starting positions when there is space, now we are putting the nodes randomly (very small differences suffice for convergence) in any case to encourage movement.

**Comment by ugurdogrusoz** [comment]
Let's discuss this please.
