### ISSUE TITLE
Layout at initialisation and after initalisation doesn't yield the same result

### ISSUE THREAD

**Issue by EliotRagueneau** [iVis-at-Bilkent/cytoscape.js-cise#25]
The layout initialised with cise layout
![Screenshot 2021-05-06 at 09 42 47](https://user-images.githubusercontent.com/42945601/117268646-6c721f80-ae4f-11eb-863a-105f0f26e273.png)

The layout executed after the network was initialised with a fcose layout.
![Screenshot 2021-05-06 at 09 40 58](https://user-images.githubusercontent.com/42945601/117268435-2cab3800-ae4f-11eb-9b95-5ebdc14fa219.png)

As you can see, when I initialise directly with the cise layout, the global space is much better used, all the disconnected subgraphs being arranged within a "compacted" square, which allows a better overview with a simple glance.
On the other hand, when I run the layout on the same graph initialised with a fcose layout, the result is totally different, with disconnected subgraphs arranged on a diagonal, and so filling a lot more space, thus having globally smaller nodes and reducing the visibility of the drawn data.

Any idea on why such different behaviour? (The used parameters are exactly the same)

**Comment by ugurdogrusoz** [comment]
@EliotRagueneau Once again, I suspect the problem is with the use of the "randomize" option. This option should be true when you call layout on a graph that hasn't been laid out before (all nodes will be at (0,0) by default, and an incremental layout with "randomize" false will give such bad "diagonal" layouts). Once a graph has been laid out though, when there are minimal changes in its topology, you want to set "randomize" to false so that the user's mental map is not destroyed by a layout from scratch.

**Comment by EliotRagueneau** [comment]
Thank you very much, it's working now!
