### ISSUE TITLE
Shift components to original location on layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#33]
When CiSE runs, it might shift the center of the drawing arbitrarily (see [this](https://github.com/ugurdogrusoz/visuall/issues/323) for an example). In order to avoid this, we should calculate the center of the drawing *before* layout and move the laid-out drawing back to this location. This should be the case for each individual component if packing is enabled.

**Comment by hasanbalci** [comment]
@ugurdogrusoz We now shift graph to its original location in both randomized and incremental layout. If packing is enabled, we first shift each individual component to its original location, then apply packing.

I added `fit` option to _demo.html_ file so that we can test whether the graph stays in its original location after layout.
