### ISSUE TITLE
Pack disconnected components

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#8]
Let's use [this extension](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities) to pack the components of disconnected graphs, just like we do with [this layout](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose) - see [its demo](https://ivis-at-bilkent.github.io/cytoscape.js-fcose/demo.html) and Pack Components to Window option in the demo.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Please check

**Comment by hasanbalci** [comment]
The logic seems true, I only realized two things:

- desiredAspectRatio option is set inside the algorithm which prevents users to enter other values. I think this extension should check whether layout-utilities is initialized by the user on the application and if it's, then it should use that instance. Otherwise, it should initialize it with default options. A check similar to one [here](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/blob/a47417cc9bbbe628474440b69122cc0dc07d95ed/src/fcose/index.js#L102). To pack components into window aspect ratio in demo, a layout-utilities instance can be initialized in demo as [here](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/blob/a47417cc9bbbe628474440b69122cc0dc07d95ed/demo.html#L104). 

-  README should be updated with the new option. An optional dependency should also be added into Dependencies section.
